#!/bin/bash

set -e
source "$PWD/scripts/osdetect"
if [[ "$OS" == "WSL" ]]; then
    echo "Detected WSL — linking WSL-specific dotfiles..."
    ln -sf "$PWD/wsl/.bashrc" "$HOME/.bashrc"
    ln -sf "$PWD/wsl/.vimrc" "$HOME/.vimrc"
    if [ ! -L "$HOME/scripts" ]; then
		[ -d "$HOME/scripts" ] && echo "Warning: '$HOME/scripts' exists and is not a symlink. Skipping..." || ln -sf "$PWD/scripts" "$HOME/scripts"
    fi
    if [ ! -L "$HOME/.config/nvim" ]; then
        [ -d "$HOME/.config/nvim" ] && echo "Warning: '$HOME/.config/nvim' exists and is not a symlink. Skipping..." || ln -sf "$PWD/wsl/.config/nvim" "$HOME/.config/nvim"
    fi
    echo "ripgrep required for nvim plugin telescope, ensure it's installed."
    ln -sf "$PWD/wsl/.tmux.conf" "$HOME/.tmux.conf"
    #ln -sf "$PWD/wsl/.dircolors" "$HOME/.dircolors"
    ln -sf "$PWD/wsl/.sqliterc" "$HOME/.sqliterc"
    git config --global core.editor "vim"
    if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
        git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
    fi
elif [[ "$OS" == "Linux" ]]; then
    echo "Detected Linux - Linking Linux-specific dotfiles..."
    ln -sf "$PWD/linux/.bashrc" "$HOME/.bashrc"
    ln -sf "$PWD/linux/.vimrc" "$HOME/.vimrc"
    if [ ! -L "$HOME/scripts" ]; then
		[ -d "$HOME/scripts" ] && echo "Warning: '$HOME/scripts' exists and is not a symlink. Skipping..." || ln -sf "$PWD/scripts" "$HOME/scripts"
    fi
    if [ ! -L "$HOME/.config/nvim" ]; then
        [ -d "$HOME/.config/nvim" ] && echo "Warning: '$HOME/.config/nvim' exists and is not a symlink. Skipping..." || ln -sf "$PWD/wsl/.config/nvim" "$HOME/.config/nvim"
    fi
    echo "ripgrep required for nvim plugin telescope, ensure it's installed."
    ln -sf "$PWD/linux/.tmux.conf" "$HOME/.tmux.conf"
    #ln -sf "$PWD/linux/.dircolors" "$HOME/.dircolors"
    ln -sf "$PWD/linux/.sqliterc" "$HOME/.sqliterc"
    git config --global core.editor "vim"
    if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
        git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
    fi
fi
