#!/bin/bash

set -e
ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
if [ ! -d "$HOME/scripts" ]
	then
		ln -sf "$PWD/scripts" "$HOME/scripts"
fi
ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/.dircolors" "$HOME/.dircolors"
ln -sf "$PWD/.sqliterc" "$HOME/.sqliterc"
git config --global core.editor "vi"
